### ISSUE TITLE
Fix references to http://macroid.github.io

### ISSUE THREAD

**Issue by stanch** [47deg/macroid#103]
I have removed the old organization and the old site (I think github still has it in cache) to avoid confusion with the new one. Could you replace the references to http://macroid.github.io with 47deg.github.io/macroid? For example:
* [x] https://github.com/47deg/macroid/blob/master/build.sbt#L76
* [x] https://github.com/47deg/macroid/blob/master/build.sbt#L84

Not sure if there are others.

**Comment by vn971** [comment]
I'm not sure it's the same issue, but links on the main README.md are broken, too:
> What does it look like
> http://macroid.github.io/Tutorial.html
404

**Comment by vn971** [comment]
Sorry, the PR explains that part. Deleting the comment.
