### ISSUE TITLE
Problem with Tweaks and find

### ISSUE THREAD

**Issue by dejvid** [47deg/macroid#67]
Hi,

I just tried this library but i stumbled on something very basic and I dont know what to do. I have really simple project with one activity  and code posted below is executed inside activity `onCreate(savedInstanceState: Bundle): Unit` method. Problem is that onClick method is not called when using macroids find method.

This code works, when i click on button `Hello1!` is printed in adb log.
```scala
    super.onCreate(savedInstanceState)
    val ui = getUi {
      l[FrameLayout](
        w[Button] <~ text("Hello") <~ id(Id.button) <~ On.click(Ui {
          debug("Hello1!")
        })
      )
    }
    setContentView(ui)
```

If i write same code with find method, nothing is printed to adb log. Why is that, what am I missing?
```scala
    super.onCreate(savedInstanceState)
    val ui = getUi {
      l[FrameLayout](
        w[Button] <~ text("Hello") <~ id(Id.button)
      )
    }

   ui.find[Button](Id.button) <~ On.click(Ui{
        debug("Hello2!")
    })

    setContentView(ui)
```

Replacing `ui.find`with snippet below solves the problem, and `Hello2!` is printed to adb log. 

```scala
val but = ui.findViewById(Id.button).asInstanceOf[Button]
but.setOnClickListener(new View.OnClickListener {
  override def onClick(v: View): Unit = debug("Hello2!")
})
```

Why tweak after find does nothing?
Please help.

**Comment by stanch** [comment]
Hey,

You just need to wrap the tweaking in `runUi`:
```scala
runUi {
  ui.find[Button](Id.button) <~ On.click(Ui {
    debug("Hello2!")
  })
}
```
Note that you probably want to run this after `setContentView`.

**Comment by stanch** [comment]
Feel free to reopen if that didn’t work.
