### ISSUE TITLE
Does anyone know how to use weights in Macroid?

### ISSUE THREAD

**Issue by AbimbolaE** [47deg/macroid#74]
I found this [article](http://grokbase.com/t/gg/scala-on-android/148wfdzxz7/help-with-a-macroid-layout) but it throws a compile error `Could not find the appropriate LayoutParams constructor`

Anyone know how to achieve weights in android?

**Comment by pfn** [comment]
lp[LinearLayout] (width, height, weight)

**Comment by AbimbolaE** [comment]
Cheers!
