### ISSUE TITLE
Adding bricks in subclasses/subtraits

### ISSUE THREAD

**Issue by tymm** [47deg/macroid#81]
I have a base trait for my views in which I call `setContentView` to set a layout.
Then I have several subtraits that extend from the base trait in order to add certain layout elements.

Base trait
```
trait View[V <: IView, M <: AbstractViewModel[V]]
        extends ViewModelBaseActivity[V, M]
        with Contexts[Activity] { self: V ⇒
    def layout: Ui[android.view.ViewGroup]

    def onCreateView( state: Bundle ): Unit

    override def onCreate( state: Bundle ) = {
        super.onCreate( state )

        onCreateView( state )

        setContentView {
            getUi{
                layout
            }
        }

        setModelView( self )
    }
}
```

Subtrait:
```
trait Coordinator[V <: IView, M <: AbstractViewModel[V]]
        extends View[V, M]
        with Contexts[Activity] { self: V ⇒
    val coordinator = l[CoordinatorLayout]()

    override def onCreateView( state: Bundle ) = {
        coordinator <~ addViews(
            Seq(
                w[TextView] <~ text( "test" )
            )
        )
    }

    override val layout = coordinator
}
```

However when I create a new view which extends the Coordinator subtrait, there is no TextView displaying "test".
It works when I do the layout manipulation directly in the base trait.

**Comment by stanch** [comment]
Hey,

You need to wrap `coordinator <~ addViews(...)` into `getUi` :)

**Comment by tymm** [comment]
Ah, I need to wrap it into getUi so the tweak happens right away, right?
 
Unfortunately it doesn't help.

**Comment by javipacheco** [comment]
Maybe you should wrap it into `runUi`

```
runUi(coordinator <~ addViews(Seq(w[TextView] <~ text( "test" ))))
```

If you are using the github version, you should call to `run`

```
(coordinator <~ addViews(Seq(w[TextView] <~ text( "test" )))).run
```

I hope that this helps you

**Comment by tymm** [comment]
Thank you for the hint.
Unfortunately this also doesn't help.

**Comment by tymm** [comment]
I just did some more testing and it turns out I can't even do the following (which makes me think that it maybe has to do something with the ViewModel framework I use).

```
trait View[V <: IView, M <: AbstractViewModel[V]]
        extends ViewModelBaseActivity[V, M]
        with Contexts[Activity] { self: V ⇒
    val layout = l[CoordinatorLayout]()

    def onCreateView( state: Bundle ): Unit

    override def onCreate( state: Bundle ) = {
        super.onCreate( state )

        onCreateView( state )

        runUi {
            layout <~ addViews(
                Seq(
                    w[TextView] <~ text( "test" )
                )
            )
        }

        setContentView {
            getUi{
                layout
            }
        }

        setModelView( self )
    }
}
```

It only works if I manipulate the ViewGroup right away like `val layout = l[CoordinatorLayout]() <~ addViews(...)`

**Comment by pfn** [comment]
You're misusing layout, it is not mutable. It is a Ui[CoordinatorLayout],
not a widget you can mutate. It is effectively like a reader or IO monad

**Comment by tymm** [comment]
@pfn but it says the following in the Bricks section of the Macroid guide?

> You can add children to an empty layout later by doing
> `layout <~ addViews(button, textView, ...)`

**Comment by pfn** [comment]
Any <~ returns a new Ui, you must use the new value going forward. When all
is said and done after composing all <~ you must getUi on the final value

**Comment by tymm** [comment]
Thanks @pfn. That did the trick.
